name: Reusable Docker Workflow

on:
  workflow_call:
    inputs:
      image-name:
        description: "DockerHub image name "
        required: true
        type: string
      tag:
        description: "Image tag"
        required: false
        default: "latest"
        type: string
      cancel-old:
        description: "Cancel old runs (true = only latest commit runs, false = queue)"
        required: false
        type: boolean
        default: true
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

# ✅ Concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ inputs.cancel-old }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ inputs.image-name }}:${{ inputs.tag }}

  test:
    runs-on: ubuntu-latest
    needs: docker   # ✅ Runs only after docker job succeeds
    steps:
      - name: Run container for testing
        run: |
          docker run -d -p 5000:5000 ${{ inputs.image-name }}:${{ inputs.tag }}
          sleep 5
          curl -f http://localhost:5000 || exit 1
          
